### ISSUE TITLE
Add commands for populating the loclist or quickfix list with errors from the buffer

### ISSUE THREAD

**Issue by w0rp** [dense-analysis/ale#1810]
Some people might want to use the loclist or quickfix list for other plugins, and only populate them manually by running a command. We should add some commands for populating the loclist or quickfix list which ignore the `ale_set_loclist` and `ale_set_quickfix` values.

**Comment by smhc** [comment]
I use the following config to achieve something like this:

```vim
function! OpenALEResults()
  let bfnum = bufnr('')
  let items = ale#engine#GetLoclist(bfnum)
  call setqflist([], 'r', {'items': items, 'title': 'ALE results'})
  botright cwindow
endfunction"

function! RunALELint()
  if empty(ale#engine#GetLoclist(bufnr('')))
    let b:ale_enabled = 1
    augroup ALEProgress
      autocmd!
      autocmd User ALELintPost call OpenALEResults() | au! ALEProgress
    augroup end
    call ale#Queue(0, 'lint_file')
  else
    call OpenALEResults()
  endif
endfunction
```

However I noticed that sometimes the 'list' contains items with a bufnr of -1.
This can be the case when clangtidy detects errors in included files that aren't currently open, but includes them in the list of lint problems.

I was going to raised a separate bug but I saw this issue here.
Essentially; ale#engine#GetLoclist can return items from different, non-existent, buffers, which causes setqflist to fail with an error.

**Comment by w0rp** [comment]
Read `list.vim`. You can't just pass the `loclist` from ALE's variable to `setqflist` or `setloclist`.

**Comment by idbrii** [comment]
Here are instructions from Vim contributor yegappan on how to maintain one quickfix list instead of continually pushing new ones:

https://gist.github.com/yegappan/3b50ec9ea86ad4511d3a213ee39f1ee0

We could switch the current setqflist to this method to set our qf by id and check g:ale_set_loclist to either show our qf or ensure we haven't changed the visible qf.

(I'm not sure if setting qf by id modifies which one is visible.)

An ALEShowErrors command could open the location list to our qf. Or maybe it should set a qf id and we only populate is we have an I'd?

Regardless, I think this would ensure if you used ALEShowErrors, the location list would stay up-to-date while you edit.

**Comment by w0rp** [comment]
Thanks for the instructions.

**Comment by juanMarinero** [comment]
Solution from @smhc completed for newbies like me. Map that function:
`nnoremap <leader>erw :call OpenALEResults()<CR>`
erw from ERror Window

**Comment by idbrii** [comment]
@juanMarinero @smhc If you're still interested in this issue, please try #3761.
