### ISSUE TITLE
mypy exit code 2, shell mypy works, how to see verbose ALEInfo?

### ISSUE THREAD

**Issue by deltaskelta** [dense-analysis/ale#2703]
## Information

NVIM v0.4.0-dev
Build type: Release

Operating System: OSSierra

## What went wrong

I learned about the mypy linter so I installed it on my path and added it to ale linters. If I run the linter from the shell I see linter errors as I should, but when I run it in ALE I see the ALEInfo pasted below. 

I see there is an exit code of two but I cannot see the output. Surely there is some other output that was in stdout or stderr but I can't see what it was. 

I can recreate exit code 2 by doing `mypy .` and there is output. 

Is there a way I can see verbose output?

## Reproducing the bug

1. add mypy
2. Let ALE lint a python file with linter errors that show when mypy is run from the shell

### :ALEInfo

```
Command History:
(executable check - success) /Users/Jeff/python/reinforcement-learning-implementations/env/bin/mypy
(finished - exit code 2) ['/bin/bash', '-ic', 'cd ''/Users/Jeff/python/reinforcement-learning-implementations'' && ''/Users/Jeff/python/reinforcement-le
arning-implementations/env/bin/mypy'' --show-column-numbers  --shadow-file ''/Users/Jeff/python/reinforcement-learning-implementations/DP_04/gamblers.py
'' ''/var/folders/5q/6lv7fh7x0bv57t8m09n8j0xm0000gn/T/nvimlt7bDS/2/gamblers.py'' ''/Users/Jeff/python/reinforcement-learning-implementations/DP_04/gambl
ers.py''']
<<<NO OUTPUT RETURNED>>>
```

**Comment by richyfish** [comment]
mypy [exit code 2](https://github.com/python/mypy/pull/6738)  appears to be returned when something might be wrong with reading the file.

mypy reports the error message to stderr but the issue here is that the ALE mypy hander is not capturing stderr and therefore not reporting it.

I've added a _tiny_ [PR](https://github.com/dense-analysis/ale/pull/2706) to fix it which should give you the error output in :ALEInfo

**Comment by deltaskelta** [comment]
Cool, thanks for looking into it!
