### ISSUE TITLE
Feature request for defaulting to installed fixers like linters

### ISSUE THREAD

**Issue by trevordmiller** [dense-analysis/ale#2873]
First off, thanks so much for ALE! It is extremely helpful for me - one of the best Vim plugins out there!

The [fixing documentation](https://github.com/dense-analysis/ale#2ii-fixing) shows that using fixers currently requires manual configuration. I feel it would be nice if fixers could be set automatically like linters based on what is installed.

For example, if I'm working in a JavaScript project that has `prettier` and `eslint` in `node_modules` it would be nice if:

```vim
let g:ale_fixers = ['prettier', 'eslint']
```

Was automated in the same way linters are like:

```vim
let g:ale_linters = ['prettier', 'eslint']
```

So no manual `.vimrc` or `ftplugin` files would be needed to run `:ALEFix`.

I feel this wouldn't be disruptive to users because it would still be opt-in (via `:ALEFix` or if the user had `let g:ale_fix_on_save = 1` defined).

**Comment by w0rp** [comment]
The fixers work very differently because they can operate on multiple filetypes with the same command, so I don't think this will happen. I think it's worth making people specify which fixers they want to run, so you have to think about what your editor is doing.

The best way to share a common list of fixers with a team is to use a Vim plugin for shared configuration files, and then specify the list of fixers in the shared project file, so everyone can use the same tools. That's my suggestion for any team that wants to avoid having separate configurations for each team member.

**Comment by trevordmiller** [comment]
Sounds good. Thanks for the consideration and thanks again for the great plugin!
