### ISSUE TITLE
Add ability to pass options to tsserver

### ISSUE THREAD

**Issue by tmccombs** [dense-analysis/ale#2901]
I'm running into a problem where typescript runs out of memory, and would like to pass in the `-max_old_size` option to increase the maximum heap size, but I can't figure out a way to do that. Possibly I could use the `g:ale_typescript_tsserver_config_path` option, but I can't find any documentation on the format for this `tsserver.json` file, or how to use it to configure tsserver.

**Comment by sirupsen** [comment]
Ran into the same issue where `tsserver` doesn't work due to a low max old size.

For now, use this work-around. Change `/usr/local/bin/tsserver` (after installing `tsserver` globally) to pass the option you need to increase 

```
#!/usr/bin/env node --max-old-space-size=4096
require('../lib/tsserver.js')`
```

Then in your `vimrc`:

```
let g:ale_typescript_tsserver_executable = 'tsserver'
```

To force it to use the global executable you've changed (you could do this with the one in `node_modules/.bin` as well)

**Comment by w0rp** [comment]
You can control the size of the heap space for node via an environment variable.

```
export NODE_OPTIONS='--max_old_space_size=4096'
```

That's the best way to increase the heap size for a machine.

**Comment by sirupsen** [comment]
Excellent @w0rp, thanks!

And thank you for ALE ❤️
