### ISSUE TITLE
Change the default "ale_rust_rustc_options" value!!!!

### ISSUE THREAD

**Issue by Godnyx** [dense-analysis/ale#3044]
I had a big issue making Rust work with ALE! After trying SO many things and spending tons of hours, found that the error was the default value of the option "ale_rust_rustc_options". Why the default option is set to work only with nightly build? Who told you that people use nightly and you have it as default? It makes total sense to have the stable as the default version!

But that's not my problem... My real problem is that you don't mention what we should use for the stable version and I had to spend tons of hours to fix my problem. I had to "guess" that I must set this option empty ('') to work. 

I totally respect and like work so this is why I'm point this out. I also tried to get help from Reddit and no one was able to solve the problem. One people said about this option and he said "Someone should tell them to change the default option". So I am telling you! Or at least change the documentation!

**Comment by w0rp** [comment]
It was the way people most commonly ran `rustc` for a long time. I'm happy to change the default later, if it doesn't break anything for a lot of people. It's difficult to ever change default options, as doing so is a breaking change for a lot of people.

The documentation is fine. If you type `:help ale-rust` and press Page Down twice, you'll see the documentation for the option, which is also shown in `:ALEInfo`.

**Comment by Godnyx** [comment]
Thanks for your answer and for telling me about :help ale-rust. And sorry for the late answer but for some reason I didn't got any notification. As from now that I know that you've noticed this, I'm gonna close it. Thanks for your answer and your effort!

**Comment by damofthemoon** [comment]
Hello @w0rp ,

I'm new with both ALE (I use it since 1 week, **fantastic plugin**!) and Rust (few days). I was also confused the plugin seems broken for Rust while working out of the box for all other languages I use. 

Would you be ok for a PR exposing that point in the README, like you do for C/C++ configuration for instance? Small section explaining ALE use nightly build by default and how to overcome the "issue" :

1. Setup Rust to use nightly build by default (`rustup default nightly`)
2. Setup ALE to use stable build options (`let g:ale_rust_rustc_options=""`)

Damien
