### ISSUE TITLE
Add support for svelte

### ISSUE THREAD

**Issue by repomaa** [dense-analysis/ale#3138]
I've added support for svelte or so i thought with in my fork https://github.com/repomaa/ale

I need some help testing it out. Currently I don't see the svelteserver linter anywhere in the list of available linters for the filetype svelte. It uses stylelint and eslint instead. Any clues why this might be the case?

**Comment by repomaa** [comment]
https://github.com/dense-analysis/ale/compare/master...repomaa:svelte Here's a direct link to the changes

**Comment by rasmusmerzin** [comment]
I tried to use this but could not find `svelteserver` executable. It seems that this patch predates Svelte support for Typescript as now there is `svelte-check`. I'm not really sure if `svelte-check` support should be added to ALE or should typescript support be added to `eslint-plugin-svelte3`. I would definitely love to see svelte typescript linting in Vim since it seems that Svelte team focuses more on VSCode.

**Comment by SergeyPoluektov** [comment]
Just tried it out. Everything works perfect with `svelteserver` and typescript. Completion, linting, go to definition. Amazing work @repomaa :tada: Looking forward to have this change merged!

> I tried to use this but could not find svelteserver executable.

I suppose you have to install `svelte-language-server` to be able to use it. The same way it works for `tsserver` for instance.

**Comment by rasmusmerzin** [comment]
I see! Apologies for being ignorant.

**Comment by w0rp** [comment]
I've merged the PR now.

**Comment by gmuresan** [comment]
@repomaa I'm not seeing svelteserver in my list of enabled linters when running `:ALEInfo`. Is there a setting I may be forgetting in my .vimrc?

**Comment by Arro** [comment]
I'm also not seeing `svelteserver` in the list when running `:ALEInfo`. 

Also, shouldn't the linter be running `svelte-check`?  In my terminal, r unning `svelte-check` produces errors, `svelteserver` returns nothing.

**Comment by niknah** [comment]
I am getting a "Parsing error: Unexpected token <" error when editing .svelte files.  Because .svelte files are now using eslint.  They are not javascript files.

**Comment by akread** [comment]
@gmuresan @Arro not sure if you sorted this out or not but I found that svelte files end up aliased under css and javascript which is why you are seeing those linters available and not the svelte ones.

This setting can be seen in `:ALEInfo` if you look for the `ale_linter_aliases` config.

In a `ftplugin/svelte.vim` I overrode that setting to svelte so that ale looked for svelte linters instead of javascript and css ones and enabled the svelteserver linter as well. After that it all worked as expected. Find the filetype plugin configuration I am using below.

```
let b:ale_linter_aliases = ['svelte']
let b:ale_linters = ['svelteserver']
```

Likely these aliases should be adjusted in the ale repo so this works as expected out of box.
