### ISSUE TITLE
Add example for a custom command fixer

### ISSUE THREAD

**Issue by skorokithakis** [dense-analysis/ale#3167]
I wrote a program that accepts code in stdin and writes the fixed code in stdout. However, I'm not sure how to add it as a fixer to Ale. Could a simple example be added to the README on how to do this, since most custom tools read from stdin and write to stdout anyway?

I think it would be useful for many users, as it's a fairly common scenario.

**Comment by skorokithakis** [comment]
Can someone tell me how to do this so I can add formatters for various files, at least?

**Comment by hsanson** [comment]
Look at this PR that adds astyle fixer to ALE. This is a very simple example on how to do what you want:

  - https://github.com/dense-analysis/ale/pull/3231

**Comment by skorokithakis** [comment]
That looks great, thanks!

**Comment by skorokithakis** [comment]
Looking at that example, I have a question: Is there no simple case where I can add some configuration line to my `.vimrc` and have Ale use an executable that accepts files in stdin and prints formatted files to stdout? Since that's a very common interface for fixers, I would expect that I'd be able to just specify any custom tool in that way.

Is this possible already? Should I open an issue if not?

**Comment by hsanson** [comment]
Check this function:

```
:h ale#fix#registry#Add
```

**Comment by roginfarrer** [comment]
Just did this to add `luafmt`. I agree, there's no good clear documentation on this (esp. if you're not super familiar with vimscript). Here's what I did:

```vim
function! FormatLua(buffer) abort
    return {
    \   'command': 'luafmt --stdin'
    \}
endfunction

execute ale#fix#registry#Add('luafmt', 'FormatLua', ['lua'], 'luafmt for lua')

" You can now use it in g:ale_fixers
let g:ale_fixers = {
  \ 'lua': ['luafmt']
}
```

**Comment by skorokithakis** [comment]
@roginfarrer that's exactly what I needed, thanks!

Someone please add that to the documentation?

**Comment by gennaro-tedesco** [comment]
Is it possible to have more information about where exactly the function definition for new formatters must be placed, within one's own vim configuration? By replicating the example above I get an exception of "no fixer named <name>" - which leads me to believe that `execute ale#fix#registry#Add` did not really add the new function to the registry.

**Comment by msdos** [comment]
I too had a problem with this snippet but decided to debug my custom command and the problem was with my configuration, not ale. Some tips for debugging:

- Call the command in your shell, to check if it's available in your path. If it's not, ale won't find it;
- Always check from where your fixer is receiving it's parameters. In the example, luafmt is using --stdin cause it's coming from vim, but if you don't have an explicit option like that, maybe just adding `my_custom_fixer -` will suffice.

What I would suggest to @w0rp, if possible, is to add information in `ALEInfo` about custom called fixers... no errors were shown to me so it was a trial and error approach. Funny thing is I used https://github.com/vim-autoformat/vim-autoformat to check if there was an error in ale or in my custom fixer.
