### ISSUE TITLE
Document how to specify rubocop linter options

### ISSUE THREAD

**Issue by jmgarnier** [dense-analysis/ale#3169]
Looking at https://github.com/dense-analysis/ale/blob/master/ale_linters/ruby/rubocop.vim and thanks to `:ALEInfo` command, I found out how to pass rubocop options.

Sharing my custom setup of rubocop for others ruby developers can google it:

```vim
Plug 'dense-analysis/ale'

" Set specific linters
let g:ale_linters = {
\   'ruby': ['ruby', 'rubocop'],
\}

" Only run linters named in ale_linters settings.
let g:ale_linters_explicit = 1

" Run linters only when I save files
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
" if you don't want linters to run on opening a file
let g:ale_lint_on_enter = 0

" Disable ALE auto highlights
let g:ale_set_highlights = 0 
let g:airline#extensions#ale#enabled = 1

let g:ruby_rubocop_options = "--config .rubocop.yml --force-exclusion"

```

I can also push a PR to some documentation some other day

**Comment by hsanson** [comment]
By default ALE sets `--force-exclusion` and the `.rubocop.yml` is automatically used if present in the current path by rubocop. ALE should work properly for ruby/rails projects without need to set `g:ruby_rubocop_options`.

**Comment by jmgarnier** [comment]
Strange. Thanks for your quick reply. I will come back to it next time I play with my vim config

**Comment by jmgarnier** [comment]
You are right. 

The problem was:
>  rubocop /app/models/ability.rb --force-exclusion
Error: unrecognized cop Performance/RedundantMatch found in .rubocop.yml, unrecognized cop Performance/StringReplacement found in .rubocop.yml

There were some garbages in the .rubocop.yml and it failed silently. Maybe ALE could check the exit code of `rubocop` comment ?

In the meanwhile, I will ask my team why nobody noticed it ;) ???

**Comment by hsanson** [comment]
ALE checks the exit codes and parses the output of the linters if it is not zero.  In this case it also does it but the errors reported do not match ALE's error parser so they are not detected. Even if they did the errors are not in the current buffer, instead they are on the config file itself. Since ALE works only on the current buffer there is no defined way to report linter errors.  That is why ALEInfo is very important to debug these.

Appreciated if you can close this issue if solved.
