### ISSUE TITLE
AsciiDoc LanguageTool 

### ISSUE THREAD

**Issue by WojciechRydel** [dense-analysis/ale#3220]
Hi!
I would like to suggest to add LanguageTool linter for AsciiDoc files. The linter is enabled by default for Markdown files, and having it enabled for AsciiDoc as well, will be really nice!

**Comment by hsanson** [comment]
Though I wish there were linters or language servers for Asciidoc, unfortunately there are none as far as I know. I do know some talks about these have been around for years but still far from materializing:

   - https://github.com/asciidoctor/asciidoctor/issues/3630
   - https://github.com/asciidoctor/asciidoctor-extensions-lab/issues/6

I such tool becomes available this issue can be reopen and I will most likely add it to ALE since I use Asciidoc daily at work and to keep my personal notes.

**Comment by WojciechRydel** [comment]
Hi @hsanson ,
I think that I have not made myself clear . What I would like to be added in ALE for AsciiDoc is [LanguageTool](https://languagetool.org) support, the same way it [is available for Markdown](https://github.com/dense-analysis/ale/blob/master/ale_linters/markdown/languagetool.vim) - #2155. Correct me if I am wrong, but I think that the enhancement does not require any language server for AsciiDoc itself.

**Comment by hsanson** [comment]
@WojciechRydel you are correct, I totally misunderstood the issue.  I created a PR that enables LanguageTool for asciidoc documents. Was easy to do since the code is already generic and used for both mail and markdown documents.

Note I do not use this tool so I have not tested this and would appreciate if you can test it to ensure it is working properly.

**Comment by jimisola** [comment]
LSP created for MarkDown: https://code.visualstudio.com/blogs/2022/08/16/markdown-language-server

Guessing that there are some similarities.
