### ISSUE TITLE
Please add Release Version in the ALEInfo output

### ISSUE THREAD

**Issue by bgmonroe** [dense-analysis/ale#3236]
I don't see any easy way to see which release version of ale I have.  It would be useful to be able to quickly look it up in the ALEInfo output.
Thanks!

**Comment by RyanSquared** [comment]
I imagine a lot of people are going to just use the ALE master instead of a specific tagged release. I'm also not sure if ALE can tell from where it is loaded, or if it's even loaded from Git. If you need to figure out what commit you're currently on, you could use `git log --format=%H -1`, and if you want to see which version, you can use `git status` to show where HEAD is detached to.

We also can't really include it in the commit, given we don't know the sha1 for the commit until the commit itself is made. I'm not entirely sure how it could be implemented.

**Comment by bgmonroe** [comment]
Thanks for the quick response, Ryan.  I had seen, in the API documentation, that it "looks" like there is support with the ale#Has function:
```
  ALE versions can be checked with version strings in the format
  `ale#Has('ale-x.y.z')`, such as `ale#Has('ale-2.4.0')`.
```
I assumed that the git release tag was embedded in ALE....somewhere to be queryable by the Has() function.  Perhaps I am mis-reading what the API doc is really saying.

**Comment by RyanSquared** [comment]
https://github.com/dense-analysis/ale/blob/master/autoload/ale.vim#L166

It is hardcoded, but it is still possible for people to be using a version later than the tagged release.

**Comment by bgmonroe** [comment]
Thanks, Ryan.  I'll close this enhancement request.  It's a bigger bag of worms that probably would be better spent on other issues and improvements.
