### ISSUE TITLE
Use `--always-make` when running `make -n`, where possible

### ISSUE THREAD

**Issue by NobodyXu** [dense-analysis/ale#3247]
Motivation:

Suppose you have a complex project that you'd like to enable `ale_c_parse_makefile`.

Now after editing the file, you run `make` then run the executable, and find the result to be unsatisfactory.

Then you enter `vim` again to edit the file, only to find there is plenty of errors due to the fact that **`make -n` no longer "run" the recipe for the source file**.

Solution:

A simple solution will be to run `make -n -W %` instead of `make -n` to ensure that **recipe for the source file is always "run"**.

This would fix the confusing behavior after `make`.

**Comment by w0rp** [comment]
How does `make -n -W %` work? What does it do? The arguments for `make` and the syntax Makefiles themselves are very esoteric.

**Comment by NobodyXu** [comment]
`make -W %` would pretend that target ‘%’ is not up-to-date, even when it is already up-to-date.

**Comment by NobodyXu** [comment]
The ‘%’ part should actually be the target that builds the software.

**Comment by NobodyXu** [comment]
`ale` can take advantage of this feature, run `make -n -W %` to extract the compiler flags, where `%` is the filename of the current buffer.

**Comment by w0rp** [comment]
I understand the issue, though I don't think what you've suggested will work. If I run `make -n | grep /bin/cc` for my [xmms2-mpris](https://github.com/w0rp/xmms2-mpris) project, I see this at first.

```
/usr/bin/cc  -I/usr/include/xmms2 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -o CMakeFiles/xmms2-mpris.dir/src/xmms2-mpris.c.o   -c /home/w0rp/git/xmms2-mpris/src/xmms2-mpris.c
/usr/bin/cc  -I/usr/include/xmms2 -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -o CMakeFiles/xmms2-mpris.dir/src/mpris-object.c.o   -c /home/w0rp/git/xmms2-mpris/src/mpris-object.c
...
```

If I run `make` and then `make -n | grep /bin/cc` again, I get nothing. If I run `make -n -W src/xmms2-mpris.c | grep /bin/cc`, I still get nothing. `make -Bn | grep /bin/cc`, however, will provide output. [This old pull request](https://github.com/dense-analysis/ale/pull/2038) was created a while ago, which used that flag, and at the time I asked for it to be tested on BSD, as `-B` has a completely different meaning on BSD.

If there's a way to detect if the system is Linux instead of BSD in Vim, without a synchronous `system` call, we can use `-B` on Linux.

**Comment by w0rp** [comment]
I think I'm just going to use `-B` if the OS is a Unix variant, but isn't Mac OSX, which is easy to detect, and offer an option to turn it off for the extreme minority of users that use a BSD OS.

**Comment by NobodyXu** [comment]
That sounds quite good for me.

**Comment by w0rp** [comment]
`--always-make` is used by default on Linux and BSD now. BSD users will probably have to set `let g:ale_c_always_make  = 0` for `make -n` parsing to work. There's no way to avoid breaking BSD `make` without making ALE worse on all other systems. If you use BSD, just set that option too.
