### ISSUE TITLE
fixer: trim_whitespace shouldn't trim escaped space

### ISSUE THREAD

**Issue by zanona** [dense-analysis/ale#3301]
Currently `trim_whitespace` will, as expected, trim all white space across lines.
However, whenever escaping the last character like `\ `, I believe it could be kept.

A good example could be a `.vimrc` file, containing:

```vim
set listchars=nbsp:☠,tab:\ \ "protect white-space trimming with a comment
```

**Comment by w0rp** [comment]
It's not possible to fix this without some complex filetype detection. I recommend writing your own replacement which behaves the way you want it to. See `:help ale-fix`. You can put your own functions in the list of fixers. For example, I use this in my `python.vim` ftplugin file.

```vim
let b:ale_fixers = [
\   'remove_trailing_lines',
\   'isort',
\   'extra_ale_fixers#AutomaticallyFixJSONDiffOutput',
\   'ale#fixers#generic_python#BreakUpLongLines',
\   'autopep8',
\]
```

One of the functions is a somewhat good, but far from perfect function for breaking up long lines in ALE. Another is a custom function I have converting JSON diff lines into Python code. (Because I copy and paste in JSON diffs a lot.)
