### ISSUE TITLE
Add option for clang-format to use a local `.clang-format` file if it exists

### ISSUE THREAD

**Issue by maujim** [dense-analysis/ale#3388]
The title is clear. I have a first draft for a possible implementation shown below. I've modified `ale/autoload/ale/fixers/clangformat.vim` and indicated which lines are new/changed. I'll submit a PR once this is sorted out.

First, we have `c_clangformat_use_local_file` to enable this option. Second, we need to be able to overwrite the `-style` flag if its provided in `c_clangformat_options` without overwriting other options. 

The easy way to get around that would be to have two variables for options for clang-format: `c_clangformat_style_options` and `c_clangformat_options`. The former would only be the flag for style and the latter would be any other command line flags that the user wants to pass. 

This method wouldn't break existing user configurations as the options variable is parsed as regular if `c_clangformat_use_local_file` isn't changed from its default.

Thoughts?

<details>
<summary>ale/autoload/ale/fixers/clangformat.vim</summary>

``` Vim
scriptencoding utf-8
" Author: Peter Renström <renstrom.peter@gmail.com>
" Description: Fixing C/C++ files with clang-format.

call ale#Set('c_clangformat_executable', 'clang-format')
call ale#Set('c_clangformat_use_global', get(g:, 'ale_use_global_executables', 0))
call ale#Set('c_clangformat_options', '')

" new
call ale#Set('c_clangformat_style_option', '')
call ale#Set('c_clangformat_use_local_file', 0)

function! ale#fixers#clangformat#GetExecutable(buffer) abort
    return ale#node#FindExecutable(a:buffer, 'c_clangformat', [
    \   'clang-format',
    \])
endfunction

function! ale#fixers#clangformat#Fix(buffer) abort
    let l:executable = ale#Escape(ale#fixers#clangformat#GetExecutable(a:buffer))
    let l:filename = ale#Escape(bufname(a:buffer))
    let l:options = ale#Var(a:buffer, 'c_clangformat_options')

	" new 
    let l:style_option = ale#Var(a:buffer, 'c_clangformat_style_option')
    let l:use_local_file = ale#Var(a:buffer, 'c_clangformat_use_local_file')

	" new
    if l:use_local_file == 1
        " should look in project root and not in working directory
        if !empty(glob('.clang-format'))
            let l:style_option = '-style=file'
        endif
    endif

    let l:command = l:executable . ' --assume-filename=' . l:filename

    if l:options isnot# ''
        let l:command .= ' ' . l:options . ' ' . l:style_option		" changed line
    endif

    return {'command': l:command}
endfunction
```

</details>

**Comment by WilliamBehrens** [comment]
I'd love to see this added, I work with many projects at once and it's not uncommon for the format guidelines to change between them, normally that's not an issue as most editors are able to format from a local file using plugins anyway, Vim is the only one I haven't seen a clean solution for.

**Comment by hsanson** [comment]
Check this snippet from the rubocop ruby fixer:

```
function! ale#fixers#rubocop#GetCommand(buffer) abort
    let l:executable = ale#Var(a:buffer, 'ruby_rubocop_executable')
    let l:config = ale#path#FindNearestFile(a:buffer, '.rubocop.yml')
    let l:options = ale#Var(a:buffer, 'ruby_rubocop_options')
    let l:auto_correct_all = ale#Var(a:buffer, 'ruby_rubocop_auto_correct_all')

    return ale#ruby#EscapeExecutable(l:executable, 'rubocop')
    \   . (!empty(l:config) ? ' --config ' . ale#Escape(l:config) : '')
    \   . (!empty(l:options) ? ' ' . l:options : '')
    \   . (l:auto_correct_all ? ' --auto-correct-all' : ' --auto-correct')
    \   . ' --force-exclusion --stdin %s'
endfunction
```

1. Use `ale#path#FindNearestFile() to search for the configuration file (e.g.  .clang_format) closest to the buffer being edited. This is preferred as it ensures the correct configuration is used when working on multiple projects without need to change the editor's current working directory.
2. No need for a flag option (e.g. 'c_clangformat_use_local_file') to enable the feature. Only if a configuration file is found it will use it in the command line call.
3. Not sure if `c_clangformat_style_option` is needed. I think the tool itself should be able to handle the case where the `-style` flag is set twice or more times. For example in rubocop if the command contains two `--config` calls it will merge them giving priority to options defined in latter files.  This is great since it would allow users to use the local configuration defined in the project and apply some overrides with another configuration of their own.
4. Ensure to add additional tests to `test_clangformat_fixer_callback.vader` for the new features.
5. Ensure to add documentation changes along with the PR.

**Comment by maujim** [comment]
I checked and the tool itself doesn't handle the case where the `-style` flag is set twice. It throws an error if the flag is used twice, so `c_clangformat_style_option` will be needed. Unfortunately this means users can't override the values from the file if they choose. 

This means we also need to keep the `use_local_file` flag so users can choose if their settings should be overridden by a `.clang-format` file.
