### ISSUE TITLE
We should be able to configure clang and gcc separately

### ISSUE THREAD

**Issue by rsachetto** [dense-analysis/ale#3413]
By reading the code, I saw that clang and gcc linters are configured with the same cc alias. In cc.vim clang is preferred over gcc. 

My suggestion is to create different configurations for clang and gcc. This would be preferred as clang has some small issues when analyzing code that was written with gcc as the main compiler. For instance, clang does not find omp.h file while gcc can find it.

Maybe add an option to prefer gcc over clang when the cc linter is active. Or maybe this option is already there and I was unable to find it.

Anyway, this is only a small suggestion. Thanks for this great software.

**Comment by w0rp** [comment]
You have to configure the `cc` linter to run one or the other. Have a look at the advice in #3299.

I merged them into one linter definition because a frequent source of issues for people was seeing strange errors from the other compiler that they weren't using, which confused a lot of people. `clang` is used over `gcc` by default because Clang prints error messages that are easier to understand. You can configure the global options to prefer `gcc` instead.
