### ISSUE TITLE
Breaking change: Make ALEToggle disable fixing

### ISSUE THREAD

**Issue by bukzor** [dense-analysis/ale#3758]
Similarly, `let g:ale_enabled=0` doesn't prevent fixers from running on save.

Expected behavior: `:ALEToggle` should prevent fixers from running, not just linters.

**Comment by w0rp** [comment]
This is by intention. Have a look through past issues for this. I am unfortunately too busy to find the right one, but it's all because `:ALEToggle` predates the existence of fixers.

I'll leave this issue open as it might be time to introduce a breaking change and add an `-option` to keep the old behaviour.

**Comment by w0rp** [comment]
I won't be changing this because there's nothing sensible that can be done which will work for everyone. When linting is disabled globally, linting isn't enabled anywhere, as per `g:ale_enabled`. When fixing is disabled globally, it can be enabled locally, and this is common, with `g:ale_fix_on_save` set to `0` and `b:ale_fix_on_save` set to `1`. If you have enabled fixing on save for only some filetypes, but not all of them, what should `:ALEToggle` or `:ALEDisable` do? Should a global option override the local one? What does re-enabling ALE after disabling it mean in that case?

There's no easy answer, so the best option for people is to write your own commands that wrap the ALE commands to do exactly what you want, they way you want it. Have a look at this guide for writing your own commands: https://dev.to/dlains/create-your-own-vim-commands-415b
