### ISSUE TITLE
Linting C/C++ headers - unused variables, non-declared, wrong types...

### ISSUE THREAD

**Issue by JuanClBl** [dense-analysis/ale#4096]
I quote the opening message of a discussion I started a few days ago:

> I have been struggling for a while trying to find out how to make ALE not to mark variables in C headers as unused, non-declared, etc, while they are being used by the .c files , declared in other headers that are called by the main .c files, etc.

> I am trying to use this plugin in Neovim and testing it with Suckless' DWM. The project compiles fine, so it does not seem logical to me that ALE marks those lines in headers as wrong. GCC is being used both for compiling and linting (no other linters installed), and from what I can see in :ALEInfo, GCC seems to be called with the current opened .h file as argument. This explains to me why all those errors appear, as GCC is trying to compile the header standalone. This is what I deduce.

> I would like to know if there is a way to configure ALE so it parses the output of the command that compiles the whole project instead of only the currently opened header. Generating compile_commands.json with bear and setting g:ale_c_parse_compile_commands has helped solving some flags issues, but not this one with the headers. Even using compdb to include headers in compile_commands.json.

Just to add some more info, the project on which I am experiencing this issue is [my custom build of DWM](https://github.com/JuanClBl/dwm). As [the original project](https://git.suckless.org/dwm/files.html), both are compiled using `make`, so it would be nice if ALE can be configured to read the project's `Makefile`, and use `make`'s output to lint the currently opened header file instead of trying to compile it standalone. Moreover, when opening a main source file like `dwm.c`, ALE properly follows all included headers and does not give any variable or type non declared errors.

**Comment by LpZ-squall** [comment]
We have a similar issue on our project, except this is just for unused static inline functions that are defined in header files (and used in .c files). I believe that for the other issues you raise, you could make it work with some (sane) changes in your code:

- if a header uses something that is defined in another header, then it should include it
- about the variables, I'm not sure to totally understand, but maybe declare them as extern in the headers?

For static inline functions declared in a header and not directly used in this header, I don't think there is a proper solution. Of course, we could disable the unused function warning to the flags given to ALE, but we do not want to do that because that could also impact the `.c` files, where we do want the check.
Would it be possible to add an option in ALE so that we can specify the flags it should use when checking a header file (that could then be different from the flags used when checking `.c` files)?

**Comment by JuanClBl** [comment]
Just got some time to work on my DWM custom build again. I have started applying your tips, and linting warnings and errors are being cleared. Many thanks. Relocating variables and libraries seems to be a good workaround to help the linter, since as I was told in the [discussions forum](https://github.com/dense-analysis/ale/discussions/4090#discussioncomment-2257971), there is no easy way to make the linter guess where those declarations are located.

I will get back once I finish relocating declarations with the remaining linting errors, if any.
